### ISSUE TITLE
Initial Setup breaks at Actions

### ISSUE THREAD

**Issue by akgoode** [Mozu/generator-mozu-actions#5] opened 2017-06-29 20:37 UTC
Hi all, I'm trying to create my first app here following the getting started guide on the Mozu website.  During the initial setup I attempted to add some actions after enabling actions on install.  I selected the domains and the actions and then the program stopped running and left me unable to make further inputs.  When I force quit the app I received this:

```
TypeError: Cannot read property 'some' of undefined
    at /Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/generator-mozu-actions/generators/action/index.js:281:37
    at Array.some (native)
    at Object.when (/Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/generator-mozu-actions/generators/action/index.js:280:36)
    at /Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/yo/node_modules/run-async/index.js:25:25
    at /Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/yo/node_modules/run-async/index.js:24:19
    at /Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:106:30
    at tryCatcher (/Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:67:31)
    at Defer.subscribeCore (/Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:2159:37)
    at Defer.tryCatcher (/Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:67:31)
    at setDisposable (/Users/andrewgoode/.nvm/versions/node/v6.9.4/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:1849:46)
```

I'm going to skip the actions through the command line for now and enable them in Dev Center and hope that works.

Edit:  I was actually unable to complete the setup at all.

**Comment by oahmed-OS** [comment] 2017-08-09 17:11
I am having the same issue. You are using Node.js V 6.9.4 correct? What version of npm do you have?

**Comment by athi94** [comment] 2017-08-21 07:09
Same issue here, using Node 6.11.2

**Comment by athi94** [comment] 2017-08-22 01:34
Okay so get Yo version 1.8.5 fixes this.

But the actual issue is due to this change in Inquirer, not sure why downgrading yo fixes it.
[Only interpret arrays of strings as object paths in question names](https://github.com/SBoudrias/Inquirer.js/pull/475)

**Comment by Vanderslice** [comment] 2017-08-22 19:17
Thanks for the report; engineering is currently looking into this issue. Able to repro this with yo 2.0.0 and confirmed yo 1.8.5 can be used as a temporary workaround.

**Comment by Vanderslice** [comment] 2017-09-14 18:30
This issue should be resolved with the latest build. Let me know if you're still running into this issue.

**Comment by Vanderslice** [comment] 2017-09-15 09:30
Going to go ahead and close this issue; if we're still seeing any new instances of this issue we can create a new bug and reference this one.

**Closed by Vanderslice** 2017-09-15 09:30 UTC
